name: Playwright API Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  playwright:
    name: Playwright (Docker)
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.55.0-jammy
      options: --ipc=host
    timeout-minutes: 30

    env:
      CI: "true"
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
      BASE_URL: ${{ secrets.BASE_URL }}
      AUTH_USER: ${{ secrets.AUTH_USER }}
      AUTH_PASS: ${{ secrets.AUTH_PASS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm i
          fi

      - name: Print versions (debug)
        run: |
          node -v
          npm -v
          node -e "console.log('@@ @playwright/test version:', require('@playwright/test/package.json').version)"

      - name: Run ONLY cars.api.spec.js
        run: npx playwright test tests/api/cars.api.spec.js

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
