name: Playwright API Tests
# comment
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  playwright:
    name: Playwright (Docker)
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.55.0-jammy
      options: --ipc=host
    timeout-minutes: 30

    env:
  BASE_URL: ${{ vars.BASE_URL }}
  AUTH_USER: ${{ vars.AUTH_USER }}
  AUTH_PASS: ${{ vars.AUTH_PASS }}
  E2E_USER_EMAIL: ${{ vars.E2E_USER_EMAIL }}
  E2E_USER_PASSWORD: ${{ vars.E2E_USER_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-

      - name: Install deps
        run: npm ci

      - name: Run ONLY cars.api.spec.js (API config)
        run: npx playwright test -c playwright.api.config.js tests/api/cars.api.spec.js

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
